name: Github actions with IAM role

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: github-actions-federation
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy application via SSM
        run: |
          aws ssm send-command \
            --instance-ids i-0f0ce7548145af848 i-0f8a340fbceaf515c \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[ "echo \"Healthy from ASG - version 30\" > /var/www/html/index.html","systemctl restart httpd"]}'
